.Dd $Mdocdate: June 9 2024 $
.Dt RLS-SERVER 1
.Os

.Sh NAME
.Nm rls-server
.Nd Remote Login Shell Server

.Sh SYNOPSIS
.Nm
.Op Fl p Ar port
.Op Fl m Ar maxconn

.Sh DESCRIPTION
.Nm
is a server that allows (remote)
.Nm rls
clients to connect to and obtain a shell on this host. 
.Pp
Client-server communication is 
.Em unencrypted . 
Therefore, it is strongly recommended to make sure that such a communication is 
between two trusted hosts over a secure network.
.Pp

Options:

.Bl -tag -width Ds
.It Fl p Ar port
Use
.Ar port
as the TCP port to listen for clients. This overrides the default which is 513.

.It Fl m Ar maxconn
Use
.Ar maxconn
as the highest number of simultaneously supported connections. This overrides the default which is 16.

.El
.Pp
To shutdown the server type quit. Alternatively, Ctrl+C or Ctrl+\\ may be used.

.Sh FILES
.Bl -tag -width Ds
.It Em /usr/local/etc/rls-server/rls-server.conf
.Nm rls-server
configuration file. See
.Xr rls-server(7) .
.El

.Sh EXIT STATUS
.Nm
exits with 1 if an error occurred, 0 otherwise.

.Sh NOTES
See
.Xr rls-server(7)
for a detailed explanation of how
.Nm
works.

.Sh SEE ALSO
.Xr rls(1)
.Xr rls(7)
.Xr rls-server(7)

.Sh AUTHOR
.An Leonardo Brugnano Aq Mt brugnano.2128518@studenti.uniroma1.it
